/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhuanmibao_ZMBJni */

#ifndef _Included_com_zhuanmibao_ZMBJni
#define _Included_com_zhuanmibao_ZMBJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhuanmibao_ZMBJni
 * Method:    crypto
 * Signature: ([BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zhuanmibao_ZMBJni_crypto
  (JNIEnv *, jclass, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
